---
language: ruby
script: "bundle exec rake validate && bundle exec rake lint && bundle exec rake spec SPEC_OPTS='--format documentation'"
bundler_args: --without development
matrix:
  fast_finish: true
  include:
    - rvm: 2.4.0
      env: PUPPET_VERSION=5.5.17
    - rvm: 2.4.0
      env: PUPPET_VERSION=6.10.0
sudo: false
