source 'https://rubygems.org'

gem 'puppet', ENV.key?('PUPPET_VERSION') ? "~> #{ENV['PUPPET_VERSION']}" : '>= 5.5.17'

gem 'rake'
gem 'rspec', '~> 3.9.0'
gem 'rspec-puppet', '~> 2.7.8'
gem 'rspec-puppet-facts', '>= 1.9.6'
gem 'puppetlabs_spec_helper', '>= 2.14.1'
gem 'puppet-lint'
gem 'puppet-lint-absolute_classname-check'
gem 'puppet-lint-absolute_template_path'
gem 'puppet-lint-appends-check'
gem 'puppet-lint-classes_and_types_beginning_with_digits-check'
gem 'puppet-lint-empty_string-check'
gem 'puppet-lint-file_ensure-check'
gem 'puppet-lint-leading_zero-check'
gem 'puppet-lint-numericvariable'
gem 'puppet-lint-param-docs', '>= 1.5.0'
gem 'puppet-lint-resource_reference_syntax'
gem 'puppet-lint-spaceship_operator_without_tag-check'
gem 'puppet-lint-strict_indent-check'
gem 'puppet-lint-trailing_comma-check'
gem 'puppet-lint-undef_in_function-check'
gem 'puppet-lint-unquoted_string-check'
gem 'puppet-lint-usascii_format-check'
gem 'puppet-lint-variable_contains_upcase'
gem 'puppet-lint-version_comparison-check'
gem 'simplecov'
gem 'puppet-blacksmith'
gem 'json'
gem 'json_pure'
gem 'metadata-json-lint'
gem 'webmock'
gem 'addressable'
gem 'oauth'
gem 'parallel_tests'